---
values:
  elastic-version: 7.2.0
  support-diagnostics-version: 7.0.9
  prom-exporter-version: 1.1.0
  opendistro-version: 1.2.0
  opendistro-security-version: 1.2.0.0
  opendistro-alerting-version: 1.2.0.0
  opendistro-sql-version: 1.2.0.0
  opendistro-performance-analyzer-version: 1.2.0.0
  elasticsearch-openjdk-version: 11.0.2