---
values:
  elastic-version: 7.3.2
  support-diagnostics-version: 7.0.9
  prom-exporter-version: 1.1.0
  opendistro-version: 1.3.0
  opendistro-security-version: 1.3.0.0
  opendistro-alerting-version: 1.3.0.1
  opendistro-index-management-version: 1.3.0.1
  opendistro-sql-version: 1.3.0.0
  opendistro-job-scheduler-version: 1.3.0.0
  opendistro-performance-analyzer-version: 1.3.0.0
  elasticsearch-openjdk-version: 11.0.2